### ISSUE TITLE
Client should return etag when retrieving policy file

### ISSUE THREAD

**Issue by hosom** [tailscale/tailscale-client-go#119]
At the moment, the client does not appear to return the ETag value to be used in a later `If-Match`. Ideally, this information should be surfaced so that consumers of this library are able to make use of the already existing ability to specify an `ETag` when writing a new policy file to the API.

**Comment by oxtoacart** [comment]
@hosom The v2 API now returns the current `ETag` on the [ACL](https://pkg.go.dev/github.com/tailscale/tailscale-client-go/v2#ACL) and [RawACL](https://pkg.go.dev/github.com/tailscale/tailscale-client-go/v2#RawACL).
