### ISSUE TITLE
Bad request when creating auth keys

### ISSUE THREAD

**Issue by jsiebens** [tailscale/tailscale-client-go#35]
Since the new release 1.7.0, creating an auth key returns a 400 bad request:

`json: unknown field "expirySeconds" (400)`

Previous version 1.6.0 creates the key successfully.

**Comment by davidsbond** [comment]
Looks like https://github.com/tailscale/tailscale-client-go/pull/34 put the field in the incorrect part of the request according to the API documentation:

Here's an example of what the above change produces:

```json
{
  "capabilities": {
    "devices": {
      "create": {
         "expirySeconds": 1440
      }
    }
  }
}
```

Here's what the API documentation expects:

```json
{
  "capabilities": {
    "devices": {
      "create": { }
    }
  },
  "expirySeconds": 1440
}
```
