### ISSUE TITLE
Support setting comment for ACL

### ISSUE THREAD

**Issue by matshch** [tailscale/tailscale-client-go#41]
There is a feature that allows to block ACL edits from admin console by specifying special comment in the top of the ACL: https://tailscale.com/kb/1204/gitops-acls/#prevent-others-from-accidentally-modifying-your-tailnet-policy-file
However, there is no way to pass such comment when using `Client`'s `SetACL()` method, because it only accepts `ACL` structure. Maybe it could be added via `SetACLOption`?

After adding it here it would be nice to add the same feature in https://github.com/tailscale/terraform-provider-tailscale.

**Comment by bradfitz** [comment]
We should also stop maintaining two clients and migrate the terraform provider to use https://pkg.go.dev/tailscale.com/client/tailscale
