### ISSUE TITLE
feat: Add support for a custom `http.Client`

### ISSUE THREAD

**Issue by erezrokah** [tailscale/tailscale-client-go#79]
Thank you for this lovely project 👋 

Would it be possible to add an option to configure the `http.Client` set in:
https://github.com/tailscale/tailscale-client-go/blob/b40c082c85b730c5976bcf283ab99495673a667f/tailscale/client.go#L77

This is useful for implementing retries via https://github.com/hashicorp/go-retryablehttp

**Comment by oxtoacart** [comment]
This is now available in the in-progress V2 API.

**Comment by erezrokah** [comment]
Hi @oxtoacart 👋 Thanks for the update. When is v2 scheduled to be released?

**Comment by oxtoacart** [comment]
> Hi @oxtoacart 👋 Thanks for the update. When is v2 scheduled to be released?

We don't have a firm date. The current pre-release is complete in terms of which APIs are covered, but we'll likely have a round of tweaking/cleanup before we release.
